### ISSUE TITLE
使用全局类型声明.d.ts，无法解析到

### ISSUE THREAD

**Issue by yiqianglin** [diy4869/otaku-ui#5]
您好，拜读了文章：【通过一个需求来深入 TypeScript 编译原理】：https://juejin.cn/post/7117451638956097549
受益很大，我在自己的需求（获取一个ts文件入口的所有依赖）中，参考了一下，发现有一个疑问：如果引用了types/***.d.ts的引用声明，generator解析出来的类型并没有包含全局的类型；
请问这一个能怎么解决，希望得到指引或者修改，不胜感激！

**Comment by diy4869** [comment]
确实不会包含，因为就没做处理，对于组件来讲，大部分是放在当前文件，或者引入的其他文件，所以就没做处理，其余还有 interface 的 同名合并问题，type 的 一些复杂规则也没做处理。如果要做处理的话，可以通过glob 去做，匹配全局 d.ts 处理就行了，我这个也只是处理了我用到的情况，官方也有地方说明类型解析规则，可以去参考那个进行处理。如果没什么特殊情况的话，不建议放全局，主要找的时候比较麻烦，虽然 ts 会给你负责解析。
